---
- hosts: all
  become: yes
  roles:
    - role: common

- hosts: nodo1
  become: yes
  roles:
    - role: database

- hosts: nodo1
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  roles:
    - role: poblar_db

- hosts: nodo1
  become: yes
  roles:
    - role: dns

- hosts: nodo2
  become: yes
  roles:
    - role: servidorWeb
- hosts: nodo2
  become: yes
  roles:
    - role: drush
