---
- name: Instalación de apache2, PHP , unzip y cliente de postgresql
  apt: name={{ item }} state=latest
  loop:
    - apache2
    - php7.0
    - php7.0-pgsql
    - php7.0-gd
    - php7.0-mbstring
    - unzip
    - php7.0-xml
    - postgresql-client    

- name: Virtualhost
  template: src=drupal.conf dest=/etc/apache2/sites-available/drupal.conf
  notify: restart apache2

- name: Activacion del sitio
  shell: a2ensite drupal.conf
  notify: restart apache2  

- name: Añadiendo Modulo apache
  shell: a2enmod rewrite
  notify: restart apache2
